### ISSUE TITLE
Not catching unhandled errors in create-react-app

### ISSUE THREAD

**Issue by ghost** [bugsnag/bugsnag-react#19] opened 2018-10-31 18:07 UTC
### Expected behavior
Catch unhandled errors and network errors, like Sentry.

### Observed behavior
Does not catch unhandled and network errors.

The only errors that bugsnag catches in my app are `render` errors. Errors that come from a promise are not caught. Network errors are not caught.

### Steps to reproduce
1. Create a react app with create-react-app 1.x
2. Install bugsnag and bugsnag-react, set them up according to docs.
```js
const bugsnagClient = bugsnag(config);
export const ErrorBoundary = bugsnagClient.use(bugsnagReact(React));
export default ErrorBoundary;
```

### Version
bugsnag-js v4.7.3

bugsnag-react v1.1.1

**Comment by bengourley** [comment] 2018-11-27 17:13
Hi @waynebloss can you provide more steps to reproduce the errors that you mention (network and unhandled)? Or write in to support@bugsnag.com if you want us to take a look at your account.

We would expect Bugsnag to report unhandled exceptions and unhandled promise rejections. Network errors are not considered "errors" but are rather recorded as breadcrumbs.

Thanks

**Comment by bengourley** [comment] 2018-11-27 17:14
I'm closing this issue because the repo is about to be archived. Get in touch via support or [@bugsnag/js](https://github.com/bugsnag/bugsnag-js/issues) if you're still having issues.

**Closed as completed by bengourley** 2018-11-27 17:14 UTC
